package Perinci::CmdLine::Manual::HowTo::Completion; # just to make podweaver happy

# AUTHORITY
# DATE
# DIST
# VERSION

1;
# ABSTRACT: How-to guides related to completion

=head1 DESCRIPTION

In a Perinci::CmdLine-based CLI program, shell tab completion is mostly the
issue of completing function arguments. A sample Rinci function metadata:

 {
   v => 1.1,
   summary => 'A foo utility',
   args => {
     bar => { ... },
     baz => { ... },
   }
 }

Function argument names are simple, they are just taken from list of function
arguments in the Rinci function metadata:

 % myprog --ba<tab>
 bar      baz

Completing function argument values is where the meat is. Completion can come
from simple sources like schema:

 bar => { schema => ['str', in => ['one', 'two', 'three']], ... }

 % myprog --bar <tab>
 one      three        two

or more complex sources.


=head2 Completion from argument schema

TODO

=head2 Completion from configuration

TODO

=head2 Completion from custom completion routine

TODO


=head1 SEE ALSO

L<Log::ger>
